[project]
name = "td-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
    "tdp-examplecomp>=0.7",
    "tdp-jsonconfig>=2.14",
    "tdp-queriedwebclient>=1.11",
]

[[tool.uv.index]]
url = "https://test.pypi.org/simple/"
